// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CentinelaV3.Data.npsql
{
    public partial class Ccbeca
    {
        public int Beid { get; set; }
        public string Beusario { get; set; }
        public short? Beperiodo { get; set; }
        public short? Beanio { get; set; }
        public decimal? Beinscrip { get; set; }
        public decimal? Beparcialidades { get; set; }
        public string Conceptoid { get; set; }
        public string Bcid { get; set; }
        public string Betipo { get; set; }
        public string Beestatus { get; set; }
        public short? Beconfirma { get; set; }
        public DateTime? Beconfecha { get; set; }
    }
}