// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace CentinelaV3.Data.npsql
{
    public partial class npsqlContext : DbContext
    {
        public npsqlContext()
        {
        }

        public npsqlContext(DbContextOptions<npsqlContext> options)
            : base(options)
        {
        }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseNpgsql(@"Server = interpue.com.mx; Port = 5435; Database = InterERP; User Id = pruebas; Password = Root.inter19!; Trust Server Certificate=true; Include Error Detail = true;");
        }

        public virtual DbSet<Ccbeca> Ccbeca { get; set; }
        public virtual DbSet<Taalumnoconexion> Taalumnoconexion { get; set; }
        public virtual DbSet<Talumno> Talumno { get; set; }
        public virtual DbSet<Talumnoestatus> Talumnoestatus { get; set; }
        public virtual DbSet<Tapreinscrito> Tapreinscrito { get; set; }
        public virtual DbSet<Tcrm> Tcrm { get; set; }
        public virtual DbSet<Tprospecto> Tprospecto { get; set; }
        public virtual DbSet<Tusuario> Tusuario { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasPostgresExtension("dblink");

            modelBuilder.Entity<Ccbeca>(entity =>
            {
                entity.HasKey(e => e.Beid)
                    .HasName("ccbeca_pkey");

                entity.ToTable("ccbeca");

                entity.Property(e => e.Beid)
                    .ValueGeneratedNever()
                    .HasColumnName("beid");

                entity.Property(e => e.Bcid)
                    .HasMaxLength(20)
                    .HasColumnName("bcid")
                    .HasDefaultValueSql("NULL::bpchar")
                    .IsFixedLength();

                entity.Property(e => e.Beanio).HasColumnName("beanio");

                entity.Property(e => e.Beconfecha).HasColumnName("beconfecha");

                entity.Property(e => e.Beconfirma).HasColumnName("beconfirma");

                entity.Property(e => e.Beestatus)
                    .HasMaxLength(5)
                    .HasColumnName("beestatus")
                    .IsFixedLength();

                entity.Property(e => e.Beinscrip)
                    .HasPrecision(7, 3)
                    .HasColumnName("beinscrip")
                    .HasDefaultValueSql("NULL::numeric");

                entity.Property(e => e.Beparcialidades)
                    .HasPrecision(7, 3)
                    .HasColumnName("beparcialidades")
                    .HasDefaultValueSql("NULL::numeric");

                entity.Property(e => e.Beperiodo).HasColumnName("beperiodo");

                entity.Property(e => e.Betipo)
                    .HasMaxLength(5)
                    .HasColumnName("betipo")
                    .IsFixedLength();

                entity.Property(e => e.Beusario)
                    .HasMaxLength(10)
                    .HasColumnName("beusario")
                    .HasDefaultValueSql("NULL::bpchar")
                    .IsFixedLength();

                entity.Property(e => e.Conceptoid)
                    .HasMaxLength(20)
                    .HasColumnName("conceptoid")
                    .HasDefaultValueSql("NULL::bpchar")
                    .IsFixedLength();
            });

            modelBuilder.Entity<Taalumnoconexion>(entity =>
            {
                entity.HasKey(e => new { e.Aluid, e.Aacfid })
                    .HasName("taalumnoconexion_pkey");

                entity.ToTable("taalumnoconexion");

                entity.HasIndex(e => e.Acarid, "taalumnoconexion_acarid_idx");

                entity.Property(e => e.Aluid).HasColumnName("aluid");

                entity.Property(e => e.Aacfid).HasColumnName("aacfid");

                entity.Property(e => e.Aacfacusado).HasColumnName("aacfacusado");

                entity.Property(e => e.Aacfalergias)
                    .HasMaxLength(40)
                    .HasColumnName("aacfalergias")
                    .HasDefaultValueSql("NULL::bpchar")
                    .IsFixedLength();

                entity.Property(e => e.Aacfamaternocont)
                    .HasMaxLength(100)
                    .HasColumnName("aacfamaternocont")
                    .HasDefaultValueSql("NULL::bpchar")
                    .IsFixedLength();

                entity.Property(e => e.Aacfamunicipiocont)
                    .HasMaxLength(150)
                    .HasColumnName("aacfamunicipiocont")
                    .HasDefaultValueSql("NULL::bpchar")
                    .IsFixedLength();

                entity.Property(e => e.Aacfapaternocont)
                    .HasMaxLength(100)
                    .HasColumnName("aacfapaternocont")
                    .HasDefaultValueSql("NULL::bpchar")
                    .IsFixedLength();

                entity.Property(e => e.Aacfapellidom)
                    .HasMaxLength(50)
                    .HasColumnName("aacfapellidom")
                    .HasDefaultValueSql("NULL::bpchar")
                    .IsFixedLength();

                entity.Property(e => e.Aacfapellidop)
                    .HasMaxLength(50)
                    .HasColumnName("aacfapellidop")
                    .HasDefaultValueSql("NULL::bpchar")
                    .IsFixedLength();

                entity.Property(e => e.Aacfbachcert).HasColumnName("aacfbachcert");

                entity.Property(e => e.Aacfbachedo)
                    .HasMaxLength(50)
                    .HasColumnName("aacfbachedo")
                    .HasDefaultValueSql("NULL::bpchar")
                    .IsFixedLength();

                entity.Property(e => e.Aacfbachfin).HasColumnName("aacfbachfin");

                entity.Property(e => e.Aacfbachiller)
                    .HasMaxLength(100)
                    .HasColumnName("aacfbachiller")
                    .HasDefaultValueSql("NULL::bpchar")
                    .IsFixedLength();

                entity.Property(e => e.Aacfbachinicio).HasColumnName("aacfbachinicio");

                entity.Property(e => e.Aacfbachlugar)
                    .HasMaxLength(100)
                    .HasColumnName("aacfbachlugar")
                    .HasDefaultValueSql("NULL::bpchar")
                    .IsFixedLength();

                entity.Property(e => e.Aacfbachpais)
                    .HasMaxLength(20)
                    .HasColumnName("aacfbachpais")
                    .IsFixedLength();

                entity.Property(e => e.Aacfbachprom)
                    .HasPrecision(5, 2)
                    .HasColumnName("aacfbachprom");

                entity.Property(e => e.Aacfcallenum)
                    .HasMaxLength(80)
                    .HasColumnName("aacfcallenum")
                    .HasDefaultValueSql("NULL::bpchar")
                    .IsFixedLength();

                entity.Property(e => e.Aacfcallenumcont)
                    .HasMaxLength(120)
                    .HasColumnName("aacfcallenumcont")
                    .HasDefaultValueSql("NULL::bpchar")
                    .IsFixedLength();

                entity.Property(e => e.Aacfcedula).HasColumnName("aacfcedula");

                entity.Property(e => e.Aacfcertificado)
                    .HasMaxLength(20)
                    .HasColumnName("aacfcertificado")
                    .IsFixedLength();

                entity.Property(e => e.Aacfcolonia)
                    .HasMaxLength(120)
                    .HasColumnName("aacfcolonia")
                    .HasDefaultValueSql("NULL::bpchar")
                    .IsFixedLength();

                entity.Property(e => e.Aacfcoloniacont)
                    .HasMaxLength(120)
                    .HasColumnName("aacfcoloniacont")
                    .HasDefaultValueSql("NULL::bpchar")
                    .IsFixedLength();

                entity.Property(e => e.Aacfcomentarios)
                    .HasMaxLength(50)
                    .HasColumnName("aacfcomentarios")
                    .HasDefaultValueSql("NULL::bpchar")
                    .IsFixedLength();

                entity.Property(e => e.Aacfcurp)
                    .HasMaxLength(18)
                    .HasColumnName("aacfcurp")
                    .IsFixedLength();

                entity.Property(e => e.Aacfedocont)
                    .HasMaxLength(20)
                    .HasColumnName("aacfedocont")
                    .HasDefaultValueSql("NULL::bpchar")
                    .IsFixedLength();

                entity.Property(e => e.Aacfegreanio).HasColumnName("aacfegreanio");

                entity.Property(e => e.Aacfegreperiodo).HasColumnName("aacfegreperiodo");

                entity.Property(e => e.Aacfegresado)
                    .HasColumnName("aacfegresado")
                    .HasDefaultValueSql("0");

                entity.Property(e => e.Aacfequimat).HasColumnName("aacfequimat");

                entity.Property(e => e.Aacfestado)
                    .HasMaxLength(50)
                    .HasColumnName("aacfestado")
                    .HasDefaultValueSql("NULL::bpchar")
                    .IsFixedLength();

                entity.Property(e => e.Aacfextranjero)
                    .HasMaxLength(5)
                    .HasColumnName("aacfextranjero")
                    .IsFixedLength();

                entity.Property(e => e.Aacffacebook)
                    .HasMaxLength(120)
                    .HasColumnName("aacffacebook")
                    .IsFixedLength();

                entity.Property(e => e.Aacffb)
                    .HasMaxLength(60)
                    .HasColumnName("aacffb")
                    .IsFixedLength();

                entity.Property(e => e.Aacffechanact).HasColumnName("aacffechanact");

                entity.Property(e => e.Aacffechatitulacion).HasColumnName("aacffechatitulacion");

                entity.Property(e => e.Aacffoja)
                    .HasMaxLength(5)
                    .HasColumnName("aacffoja")
                    .IsFixedLength();

                entity.Property(e => e.Aacffojao)
                    .HasMaxLength(5)
                    .HasColumnName("aacffojao")
                    .IsFixedLength();

                entity.Property(e => e.Aacfgradoest).HasColumnName("aacfgradoest");

                entity.Property(e => e.Aacfhoratitulacion).HasColumnName("aacfhoratitulacion");

                entity.Property(e => e.Aacfmail)
                    .HasMaxLength(150)
                    .HasColumnName("aacfmail")
                    .HasDefaultValueSql("NULL::bpchar")
                    .IsFixedLength();

                entity.Property(e => e.Aacfmailt)
                    .HasMaxLength(150)
                    .HasColumnName("aacfmailt")
                    .HasDefaultValueSql("NULL::bpchar")
                    .IsFixedLength();

                entity.Property(e => e.Aacfmunicipio)
                    .HasMaxLength(120)
                    .HasColumnName("aacfmunicipio")
                    .HasDefaultValueSql("NULL::bpchar")
                    .IsFixedLength();

                entity.Property(e => e.Aacfnacionalidad)
                    .HasMaxLength(100)
                    .HasColumnName("aacfnacionalidad")
                    .IsFixedLength();

                entity.Property(e => e.Aacfnia)
                    .HasMaxLength(20)
                    .HasColumnName("aacfnia")
                    .HasDefaultValueSql("NULL::bpchar")
                    .IsFixedLength();

                entity.Property(e => e.Aacfnolibro)
                    .HasMaxLength(5)
                    .HasColumnName("aacfnolibro")
                    .IsFixedLength();

                entity.Property(e => e.Aacfnolibroo)
                    .HasMaxLength(5)
                    .HasColumnName("aacfnolibroo")
                    .IsFixedLength();

                entity.Property(e => e.Aacfnombrecont)
                    .HasMaxLength(100)
                    .HasColumnName("aacfnombrecont")
                    .HasDefaultValueSql("NULL::bpchar")
                    .IsFixedLength();

                entity.Property(e => e.Aacfnomtutor)
                    .HasMaxLength(50)
                    .HasColumnName("aacfnomtutor")
                    .HasDefaultValueSql("NULL::bpchar")
                    .IsFixedLength();

                entity.Property(e => e.Aacforiginario)
                    .HasMaxLength(100)
                    .HasColumnName("aacforiginario")
                    .IsFixedLength();

                entity.Property(e => e.Aacfoto).HasColumnName("aacfoto");

                entity.Property(e => e.AacfotoGxi)
                    .HasMaxLength(2048)
                    .HasColumnName("aacfoto_gxi")
                    .HasDefaultValueSql("NULL::character varying");

                entity.Property(e => e.Aacfpadecimientos)
                    .HasMaxLength(50)
                    .HasColumnName("aacfpadecimientos")
                    .HasDefaultValueSql("NULL::bpchar")
                    .IsFixedLength();

                entity.Property(e => e.Aacfparentescocont)
                    .HasMaxLength(30)
                    .HasColumnName("aacfparentescocont")
                    .HasDefaultValueSql("NULL::bpchar")
                    .IsFixedLength();

                entity.Property(e => e.Aacfreligion)
                    .HasMaxLength(20)
                    .HasColumnName("aacfreligion")
                    .IsFixedLength();

                entity.Property(e => e.Aacfresidente)
                    .HasMaxLength(100)
                    .HasColumnName("aacfresidente")
                    .IsFixedLength();

                entity.Property(e => e.Aacfsecedo)
                    .HasMaxLength(50)
                    .HasColumnName("aacfsecedo")
                    .HasDefaultValueSql("NULL::bpchar")
                    .IsFixedLength();

                entity.Property(e => e.Aacfseclugar)
                    .HasMaxLength(100)
                    .HasColumnName("aacfseclugar")
                    .HasDefaultValueSql("NULL::bpchar")
                    .IsFixedLength();

                entity.Property(e => e.Aacfsecundaria)
                    .HasMaxLength(100)
                    .HasColumnName("aacfsecundaria")
                    .HasDefaultValueSql("NULL::bpchar")
                    .IsFixedLength();

                entity.Property(e => e.Aacfseguro)
                    .HasMaxLength(60)
                    .HasColumnName("aacfseguro")
                    .IsFixedLength();

                entity.Property(e => e.Aacfsuspendido).HasColumnName("aacfsuspendido");

                entity.Property(e => e.Aacftelefono)
                    .HasMaxLength(150)
                    .HasColumnName("aacftelefono")
                    .HasDefaultValueSql("NULL::bpchar")
                    .IsFixedLength();

                entity.Property(e => e.Aacftelefonoc)
                    .HasMaxLength(80)
                    .HasColumnName("aacftelefonoc")
                    .IsFixedLength();

                entity.Property(e => e.Aacftelefonocont)
                    .HasMaxLength(20)
                    .HasColumnName("aacftelefonocont")
                    .HasDefaultValueSql("NULL::bpchar")
                    .IsFixedLength();

                entity.Property(e => e.Aacftelefonot)
                    .HasMaxLength(25)
                    .HasColumnName("aacftelefonot")
                    .HasDefaultValueSql("NULL::bpchar")
                    .IsFixedLength();

                entity.Property(e => e.Aacftiposangre)
                    .HasMaxLength(20)
                    .HasColumnName("aacftiposangre")
                    .HasDefaultValueSql("NULL::bpchar")
                    .IsFixedLength();

                entity.Property(e => e.Aacftipotitulacion)
                    .HasMaxLength(60)
                    .HasColumnName("aacftipotitulacion");

                entity.Property(e => e.Aacftitulado)
                    .HasColumnName("aacftitulado")
                    .HasDefaultValueSql("0");

                entity.Property(e => e.Aacftituladoanio)
                    .HasColumnName("aacftituladoanio")
                    .HasComment("\n");

                entity.Property(e => e.Aacftituladoperiodo).HasColumnName("aacftituladoperiodo");

                entity.Property(e => e.Aacftitulotesis)
                    .HasMaxLength(220)
                    .HasColumnName("aacftitulotesis")
                    .IsFixedLength();

                entity.Property(e => e.Aacftwitter)
                    .HasMaxLength(120)
                    .HasColumnName("aacftwitter")
                    .IsFixedLength();

                entity.Property(e => e.Aacfunirev)
                    .HasMaxLength(100)
                    .HasColumnName("aacfunirev")
                    .HasDefaultValueSql("NULL::bpchar")
                    .IsFixedLength();

                entity.Property(e => e.Aacgrupo)
                    .HasMaxLength(1)
                    .HasColumnName("aacgrupo");

                entity.Property(e => e.Aacmodalidad).HasColumnName("aacmodalidad");

                entity.Property(e => e.Aacsemestreactual).HasColumnName("aacsemestreactual");

                entity.Property(e => e.Aacsemestregrupo)
                    .HasMaxLength(1)
                    .HasColumnName("aacsemestregrupo")
                    .HasDefaultValueSql("NULL::bpchar");

                entity.Property(e => e.Acarid)
                    .IsRequired()
                    .HasMaxLength(20)
                    .HasColumnName("acarid")
                    .IsFixedLength();
            });

            modelBuilder.Entity<Talumno>(entity =>
            {
                entity.HasKey(e => e.Aluid)
                    .HasName("talumno_pkey");

                entity.ToTable("talumno");

                entity.HasIndex(e => e.Aluestatusid, "talumno_aluestatusid_idx");

                entity.HasIndex(e => e.Tpaident, "talumno_tpaident_idx");

                entity.Property(e => e.Aluid)
                    .ValueGeneratedNever()
                    .HasColumnName("aluid");

                entity.Property(e => e.Aluactivo).HasColumnName("aluactivo");

                entity.Property(e => e.Aluadeudo).HasColumnName("aluadeudo");

                entity.Property(e => e.Alucbravisosmor).HasColumnName("alucbravisosmor");

                entity.Property(e => e.Alucbrenviocta)
                    .HasMaxLength(1)
                    .HasColumnName("alucbrenviocta")
                    .HasDefaultValueSql("NULL::bpchar");

                entity.Property(e => e.Alucbrmorozidad).HasColumnName("alucbrmorozidad");

                entity.Property(e => e.Alucbrpedo).HasColumnName("alucbrpedo");

                entity.Property(e => e.Alucbrpolitica)
                    .HasMaxLength(5)
                    .HasColumnName("alucbrpolitica")
                    .HasDefaultValueSql("NULL::bpchar")
                    .IsFixedLength();

                entity.Property(e => e.Alucbrreporte).HasColumnName("alucbrreporte");

                entity.Property(e => e.Aluciudadnac)
                    .HasMaxLength(100)
                    .HasColumnName("aluciudadnac")
                    .IsFixedLength();

                entity.Property(e => e.Alucompany).HasColumnName("alucompany");

                entity.Property(e => e.Alucp)
                    .HasMaxLength(50)
                    .HasColumnName("alucp")
                    .IsFixedLength();

                entity.Property(e => e.Alucredfnreview)
                    .HasColumnType("timestamp without time zone")
                    .HasColumnName("alucredfnreview");

                entity.Property(e => e.Alucredfopen)
                    .HasColumnType("timestamp without time zone")
                    .HasColumnName("alucredfopen");

                entity.Property(e => e.Alucredfreview)
                    .HasColumnType("timestamp without time zone")
                    .HasColumnName("alucredfreview");

                entity.Property(e => e.Alucredlim)
                    .HasPrecision(17, 2)
                    .HasColumnName("alucredlim")
                    .HasDefaultValueSql("60000");

                entity.Property(e => e.Alucredmsg)
                    .HasMaxLength(3)
                    .HasColumnName("alucredmsg")
                    .HasDefaultValueSql("NULL::bpchar")
                    .IsFixedLength();

                entity.Property(e => e.Alucredmsgtmp)
                    .HasMaxLength(3)
                    .HasColumnName("alucredmsgtmp")
                    .HasDefaultValueSql("NULL::bpchar")
                    .IsFixedLength();

                entity.Property(e => e.Alucredopen)
                    .HasMaxLength(50)
                    .HasColumnName("alucredopen")
                    .HasDefaultValueSql("NULL::bpchar")
                    .IsFixedLength();

                entity.Property(e => e.Alucredreview)
                    .HasMaxLength(50)
                    .HasColumnName("alucredreview")
                    .HasDefaultValueSql("NULL::bpchar")
                    .IsFixedLength();

                entity.Property(e => e.Aludivision)
                    .HasMaxLength(5)
                    .HasColumnName("aludivision")
                    .HasDefaultValueSql("NULL::bpchar")
                    .IsFixedLength();

                entity.Property(e => e.Aluescprocedencia)
                    .HasMaxLength(50)
                    .HasColumnName("aluescprocedencia")
                    .HasDefaultValueSql("NULL::bpchar")
                    .IsFixedLength();

                entity.Property(e => e.Aluestado)
                    .HasMaxLength(2)
                    .HasColumnName("aluestado")
                    .IsFixedLength();

                entity.Property(e => e.Aluestatusacademico)
                    .HasColumnName("aluestatusacademico")
                    .HasDefaultValueSql("1")
                    .HasComment("Estatus AcadÃÂ©mico para Kardex\n\n***  1 Regular\n***  2 Irregular");

                entity.Property(e => e.Aluestatusid).HasColumnName("aluestatusid");

                entity.Property(e => e.Alufac).HasColumnName("alufac");

                entity.Property(e => e.Alufacdir)
                    .HasMaxLength(250)
                    .HasColumnName("alufacdir")
                    .HasDefaultValueSql("NULL::bpchar")
                    .IsFixedLength();

                entity.Property(e => e.Alufacemail)
                    .HasMaxLength(40)
                    .HasColumnName("alufacemail")
                    .HasDefaultValueSql("NULL::bpchar")
                    .IsFixedLength();

                entity.Property(e => e.Alufacfechareg).HasColumnName("alufacfechareg");

                entity.Property(e => e.Alufachorareg).HasColumnName("alufachorareg");

                entity.Property(e => e.Alufacrazons)
                    .HasMaxLength(50)
                    .HasColumnName("alufacrazons")
                    .HasDefaultValueSql("NULL::bpchar")
                    .IsFixedLength();

                entity.Property(e => e.Alufacregimen)
                    .HasMaxLength(150)
                    .HasColumnName("alufacregimen")
                    .IsFixedLength();

                entity.Property(e => e.Alufacrfc)
                    .HasMaxLength(20)
                    .HasColumnName("alufacrfc")
                    .HasDefaultValueSql("NULL::bpchar")
                    .IsFixedLength();

                entity.Property(e => e.Alufacsolicitud).HasColumnName("alufacsolicitud");

                entity.Property(e => e.Alufactipo).HasColumnName("alufactipo");

                entity.Property(e => e.Alufacusuid)
                    .HasPrecision(18)
                    .HasColumnName("alufacusuid");

                entity.Property(e => e.Alufacverificacion)
                    .HasPrecision(1)
                    .HasColumnName("alufacverificacion");

                entity.Property(e => e.Alugeneracion)
                    .HasMaxLength(2)
                    .HasColumnName("alugeneracion")
                    .HasDefaultValueSql("NULL::bpchar")
                    .IsFixedLength();

                entity.Property(e => e.Alugeneracta)
                    .HasColumnName("alugeneracta")
                    .HasDefaultValueSql("0");

                entity.Property(e => e.Aluimporte)
                    .HasPrecision(17, 2)
                    .HasColumnName("aluimporte")
                    .HasDefaultValueSql("NULL::numeric");

                entity.Property(e => e.Aluingresot)
                    .HasPrecision(9, 2)
                    .HasColumnName("aluingresot");

                entity.Property(e => e.Aluinspago)
                    .HasMaxLength(3)
                    .HasColumnName("aluinspago")
                    .HasDefaultValueSql("NULL::bpchar")
                    .IsFixedLength();

                entity.Property(e => e.Aluintereses).HasColumnName("aluintereses");

                entity.Property(e => e.Alulocalidad)
                    .HasMaxLength(250)
                    .HasColumnName("alulocalidad")
                    .IsFixedLength();

                entity.Property(e => e.Alumodalidad)
                    .HasMaxLength(10)
                    .HasColumnName("alumodalidad")
                    .HasDefaultValueSql("'PRE'::bpchar")
                    .IsFixedLength();

                entity.Property(e => e.Alumodfecha)
                    .HasColumnType("timestamp without time zone")
                    .HasColumnName("alumodfecha");

                entity.Property(e => e.Alumodhora)
                    .HasMaxLength(8)
                    .HasColumnName("alumodhora")
                    .HasDefaultValueSql("NULL::bpchar")
                    .IsFixedLength();

                entity.Property(e => e.Alumodprog)
                    .HasMaxLength(128)
                    .HasColumnName("alumodprog")
                    .HasDefaultValueSql("NULL::bpchar")
                    .IsFixedLength();

                entity.Property(e => e.Alumodusuario).HasColumnName("alumodusuario");

                entity.Property(e => e.Alumunicipio2)
                    .HasMaxLength(50)
                    .HasColumnName("alumunicipio2")
                    .HasDefaultValueSql("NULL::bpchar")
                    .IsFixedLength();

                entity.Property(e => e.Alunoant)
                    .HasMaxLength(20)
                    .HasColumnName("alunoant")
                    .HasDefaultValueSql("NULL::bpchar")
                    .IsFixedLength();

                entity.Property(e => e.Alunocontrol)
                    .HasMaxLength(20)
                    .HasColumnName("alunocontrol")
                    .HasDefaultValueSql("NULL::bpchar")
                    .IsFixedLength();

                entity.Property(e => e.Alunopro)
                    .HasMaxLength(20)
                    .HasColumnName("alunopro")
                    .HasDefaultValueSql("NULL::bpchar")
                    .IsFixedLength();

                entity.Property(e => e.Alunovant)
                    .HasMaxLength(1)
                    .HasColumnName("alunovant")
                    .HasDefaultValueSql("NULL::bpchar");

                entity.Property(e => e.Alunoverifica)
                    .HasMaxLength(1)
                    .HasColumnName("alunoverifica")
                    .HasDefaultValueSql("NULL::bpchar");

                entity.Property(e => e.Alunovpro)
                    .HasMaxLength(1)
                    .HasColumnName("alunovpro")
                    .HasDefaultValueSql("NULL::bpchar");

                entity.Property(e => e.Aluocupaciont)
                    .HasMaxLength(500)
                    .HasColumnName("aluocupaciont");

                entity.Property(e => e.Alureganio).HasColumnName("alureganio");

                entity.Property(e => e.Aluregfecha)
                    .HasColumnType("timestamp without time zone")
                    .HasColumnName("aluregfecha");

                entity.Property(e => e.Alureghora)
                    .HasMaxLength(8)
                    .HasColumnName("alureghora")
                    .IsFixedLength();

                entity.Property(e => e.Aluregperiodo).HasColumnName("aluregperiodo");

                entity.Property(e => e.Aluregprog)
                    .HasMaxLength(128)
                    .HasColumnName("aluregprog")
                    .HasDefaultValueSql("NULL::bpchar")
                    .IsFixedLength();

                entity.Property(e => e.Aluregusuario).HasColumnName("aluregusuario");

                entity.Property(e => e.Aluresidencia)
                    .HasMaxLength(250)
                    .HasColumnName("aluresidencia")
                    .IsFixedLength();

                entity.Property(e => e.Aluretenfac).HasColumnName("aluretenfac");

                entity.Property(e => e.Alusexot)
                    .HasMaxLength(1)
                    .HasColumnName("alusexot");

                entity.Property(e => e.Covid).HasColumnName("covid");

                entity.Property(e => e.Tpaident)
                    .HasMaxLength(10)
                    .HasColumnName("tpaident")
                    .HasDefaultValueSql("NULL::bpchar")
                    .IsFixedLength();
            });

            modelBuilder.Entity<Talumnoestatus>(entity =>
            {
                entity.HasKey(e => e.Alueid)
                    .HasName("PK_Estatus");

                entity.ToTable("talumnoestatus");

                entity.Property(e => e.Alueid)
                    .ValueGeneratedNever()
                    .HasColumnName("alueid");

                entity.Property(e => e.Aluestanio).HasColumnName("aluestanio");

                entity.Property(e => e.Aluestcomentario)
                    .HasMaxLength(300)
                    .HasColumnName("aluestcomentario")
                    .IsFixedLength();

                entity.Property(e => e.Aluestfecha)
                    .HasColumnName("aluestfecha")
                    .HasComment("\n");

                entity.Property(e => e.Aluesthora)
                    .HasColumnType("timestamp without time zone")
                    .HasColumnName("aluesthora");

                entity.Property(e => e.Aluestid).HasColumnName("aluestid");

                entity.Property(e => e.Aluestperiodo).HasColumnName("aluestperiodo");

                entity.Property(e => e.Aluid).HasColumnName("aluid");

                entity.Property(e => e.Usuid).HasColumnName("usuid");

                entity.HasOne(d => d.Alu)
                    .WithMany(p => p.Talumnoestatus)
                    .HasForeignKey(d => d.Aluid)
                    .HasConstraintName("FK_estatus");
            });

            modelBuilder.Entity<Tapreinscrito>(entity =>
            {
                entity.HasKey(e => new { e.Preid, e.Aluid, e.Aacfid })
                    .HasName("PK_Preinscrito");

                entity.ToTable("tapreinscrito");

                entity.Property(e => e.Preid).HasColumnName("preid");

                entity.Property(e => e.Aluid).HasColumnName("aluid");

                entity.Property(e => e.Aacfid).HasColumnName("aacfid");

                entity.Property(e => e.Preanio).HasColumnName("preanio");

                entity.Property(e => e.Prebeca).HasColumnName("prebeca");

                entity.Property(e => e.Prebecaa).HasColumnName("prebecaa");

                entity.Property(e => e.Prebecareg)
                    .HasColumnType("timestamp without time zone")
                    .HasColumnName("prebecareg");

                entity.Property(e => e.Prebecausuid).HasColumnName("prebecausuid");

                entity.Property(e => e.Predoc).HasColumnName("predoc");

                entity.Property(e => e.Predocreg)
                    .HasColumnType("timestamp without time zone")
                    .HasColumnName("predocreg");

                entity.Property(e => e.Predocusuid).HasColumnName("predocusuid");

                entity.Property(e => e.Preee).HasColumnName("preee");

                entity.Property(e => e.Preeereg)
                    .HasColumnType("timestamp without time zone")
                    .HasColumnName("preeereg");

                entity.Property(e => e.Preesquema).HasColumnName("preesquema");

                entity.Property(e => e.Preesquemareg)
                    .HasColumnType("timestamp without time zone")
                    .HasColumnName("preesquemareg");

                entity.Property(e => e.Preesquemausuid).HasColumnName("preesquemausuid");

                entity.Property(e => e.Prehorario).HasColumnName("prehorario");

                entity.Property(e => e.Prehorarioreg)
                    .HasColumnType("timestamp without time zone")
                    .HasColumnName("prehorarioreg");

                entity.Property(e => e.Prehorariousuid).HasColumnName("prehorariousuid");

                entity.Property(e => e.Prepag).HasColumnName("prepag");

                entity.Property(e => e.Prepagreg)
                    .HasColumnType("timestamp without time zone")
                    .HasColumnName("prepagreg");

                entity.Property(e => e.Prepagusuid).HasColumnName("prepagusuid");

                entity.Property(e => e.Preperiodo).HasColumnName("preperiodo");

                entity.Property(e => e.Prereg).HasColumnName("prereg");

                entity.Property(e => e.Preregreg)
                    .HasColumnType("timestamp without time zone")
                    .HasColumnName("preregreg");

                entity.Property(e => e.Pretipo)
                    .HasMaxLength(5)
                    .HasColumnName("pretipo")
                    .IsFixedLength();

                entity.HasOne(d => d.Alu)
                    .WithMany(p => p.Tapreinscrito)
                    .HasForeignKey(d => d.Aluid)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Alumno");
            });

            modelBuilder.Entity<Tcrm>(entity =>
            {
                entity.HasKey(e => e.Crmid)
                    .HasName("tcrm_pkey");

                entity.ToTable("tcrm");

                entity.HasIndex(e => e.Crmclave, "tcrm_crmclave_key")
                    .IsUnique();

                entity.HasIndex(e => e.Crmpaisid, "tcrm_crmpaisid_idx");

                entity.Property(e => e.Crmid)
                    .ValueGeneratedNever()
                    .HasColumnName("crmid");

                entity.Property(e => e.Crmactivo).HasColumnName("crmactivo");

                entity.Property(e => e.Crmamaterno)
                    .HasMaxLength(50)
                    .HasColumnName("crmamaterno")
                    .HasDefaultValueSql("NULL::bpchar")
                    .IsFixedLength();

                entity.Property(e => e.Crmapaterno)
                    .HasMaxLength(50)
                    .HasColumnName("crmapaterno")
                    .HasDefaultValueSql("NULL::bpchar")
                    .IsFixedLength();

                entity.Property(e => e.Crmcat01)
                    .HasMaxLength(8)
                    .HasColumnName("crmcat01")
                    .HasDefaultValueSql("NULL::bpchar")
                    .IsFixedLength();

                entity.Property(e => e.Crmcat02)
                    .HasMaxLength(8)
                    .HasColumnName("crmcat02")
                    .HasDefaultValueSql("NULL::bpchar")
                    .IsFixedLength();

                entity.Property(e => e.Crmcat03)
                    .HasMaxLength(8)
                    .HasColumnName("crmcat03")
                    .HasDefaultValueSql("NULL::bpchar")
                    .IsFixedLength();

                entity.Property(e => e.Crmcat04)
                    .HasMaxLength(8)
                    .HasColumnName("crmcat04")
                    .HasDefaultValueSql("NULL::bpchar")
                    .IsFixedLength();

                entity.Property(e => e.Crmcat05)
                    .HasMaxLength(8)
                    .HasColumnName("crmcat05")
                    .HasDefaultValueSql("NULL::bpchar")
                    .IsFixedLength();

                entity.Property(e => e.Crmcat06)
                    .HasMaxLength(8)
                    .HasColumnName("crmcat06")
                    .HasDefaultValueSql("NULL::bpchar")
                    .IsFixedLength();

                entity.Property(e => e.Crmcat07)
                    .HasMaxLength(8)
                    .HasColumnName("crmcat07")
                    .HasDefaultValueSql("NULL::bpchar")
                    .IsFixedLength();

                entity.Property(e => e.Crmcat08)
                    .HasMaxLength(8)
                    .HasColumnName("crmcat08")
                    .HasDefaultValueSql("NULL::bpchar")
                    .IsFixedLength();

                entity.Property(e => e.Crmcat09)
                    .HasMaxLength(8)
                    .HasColumnName("crmcat09")
                    .HasDefaultValueSql("NULL::bpchar")
                    .IsFixedLength();

                entity.Property(e => e.Crmcat10)
                    .HasMaxLength(8)
                    .HasColumnName("crmcat10")
                    .HasDefaultValueSql("NULL::bpchar")
                    .IsFixedLength();

                entity.Property(e => e.Crmclave)
                    .HasMaxLength(20)
                    .HasColumnName("crmclave")
                    .HasDefaultValueSql("NULL::bpchar")
                    .IsFixedLength();

                entity.Property(e => e.Crmcomentarios).HasColumnName("crmcomentarios");

                entity.Property(e => e.Crmcompany).HasColumnName("crmcompany");

                entity.Property(e => e.Crmcp)
                    .HasMaxLength(5)
                    .HasColumnName("crmcp")
                    .HasDefaultValueSql("NULL::bpchar")
                    .IsFixedLength();

                entity.Property(e => e.Crmdireccion)
                    .HasMaxLength(1024)
                    .HasColumnName("crmdireccion")
                    .HasDefaultValueSql("NULL::character varying");

                entity.Property(e => e.Crmedad).HasColumnName("crmedad");

                entity.Property(e => e.Crmedo).HasColumnName("crmedo");

                entity.Property(e => e.Crmedocivil)
                    .HasMaxLength(1)
                    .HasColumnName("crmedocivil")
                    .HasDefaultValueSql("NULL::bpchar");

                entity.Property(e => e.Crmfenac)
                    .HasColumnType("timestamp without time zone")
                    .HasColumnName("crmfenac");

                entity.Property(e => e.Crmimagen).HasColumnName("crmimagen");

                entity.Property(e => e.CrmimagenGxi)
                    .HasMaxLength(2048)
                    .HasColumnName("crmimagen_gxi")
                    .HasDefaultValueSql("NULL::character varying");

                entity.Property(e => e.Crmmanagercrb).HasColumnName("crmmanagercrb");

                entity.Property(e => e.Crmmanagercrd).HasColumnName("crmmanagercrd");

                entity.Property(e => e.Crmmodfecha)
                    .HasColumnType("timestamp without time zone")
                    .HasColumnName("crmmodfecha");

                entity.Property(e => e.Crmmodhora)
                    .HasMaxLength(8)
                    .HasColumnName("crmmodhora")
                    .HasDefaultValueSql("NULL::bpchar")
                    .IsFixedLength();

                entity.Property(e => e.Crmmodprog)
                    .HasMaxLength(128)
                    .HasColumnName("crmmodprog")
                    .HasDefaultValueSql("NULL::bpchar")
                    .IsFixedLength();

                entity.Property(e => e.Crmmodusuario).HasColumnName("crmmodusuario");

                entity.Property(e => e.Crmmoneda)
                    .HasMaxLength(8)
                    .HasColumnName("crmmoneda")
                    .HasDefaultValueSql("NULL::bpchar")
                    .IsFixedLength();

                entity.Property(e => e.Crmmotivo).HasColumnName("crmmotivo");

                entity.Property(e => e.Crmmunicipio).HasColumnName("crmmunicipio");

                entity.Property(e => e.Crmnacionalidad)
                    .HasMaxLength(50)
                    .HasColumnName("crmnacionalidad")
                    .HasDefaultValueSql("NULL::bpchar")
                    .IsFixedLength();

                entity.Property(e => e.Crmnombre)
                    .HasMaxLength(50)
                    .HasColumnName("crmnombre")
                    .HasDefaultValueSql("NULL::bpchar")
                    .IsFixedLength();

                entity.Property(e => e.Crmpaisid).HasColumnName("crmpaisid");

                entity.Property(e => e.Crmregfecha)
                    .HasColumnType("timestamp without time zone")
                    .HasColumnName("crmregfecha");

                entity.Property(e => e.Crmreghora)
                    .HasMaxLength(8)
                    .HasColumnName("crmreghora")
                    .HasDefaultValueSql("NULL::bpchar")
                    .IsFixedLength();

                entity.Property(e => e.Crmregprog)
                    .HasMaxLength(128)
                    .HasColumnName("crmregprog")
                    .HasDefaultValueSql("NULL::bpchar")
                    .IsFixedLength();

                entity.Property(e => e.Crmregusuario).HasColumnName("crmregusuario");

                entity.Property(e => e.Crmsexo)
                    .HasMaxLength(1)
                    .HasColumnName("crmsexo")
                    .HasDefaultValueSql("NULL::bpchar");
            });

            modelBuilder.Entity<Tprospecto>(entity =>
            {
                entity.HasKey(e => e.Prsid)
                    .HasName("tprospecto_pkey");

                entity.ToTable("tprospecto");

                entity.HasIndex(e => e.Prsedoescuela, "itprospecto1");

                entity.HasIndex(e => e.Prscarrera2, "itprospecto10");

                entity.HasIndex(e => e.Campid, "itprospecto11");

                entity.HasIndex(e => e.Covid, "itprospecto12");

                entity.HasIndex(e => e.Usuid, "itprospecto13");

                entity.HasIndex(e => e.Prsestatus, "itprospecto2");

                entity.HasIndex(e => e.Prsmedio, "itprospecto3");

                entity.HasIndex(e => e.Prsmodalidad, "itprospecto4");

                entity.HasIndex(e => e.Prsestudio, "itprospecto5");

                entity.HasIndex(e => e.Prscarrera, "itprospecto6");

                entity.HasIndex(e => e.Prsmunesc, "itprospecto7");

                entity.HasIndex(e => e.Prsescuela, "itprospecto8");

                entity.HasIndex(e => e.Prscarrera3, "itprospecto9");

                entity.Property(e => e.Prsid).HasColumnName("prsid");

                entity.Property(e => e.Campid).HasColumnName("campid");

                entity.Property(e => e.Covid).HasColumnName("covid");

                entity.Property(e => e.Prsactividad)
                    .HasMaxLength(20)
                    .HasColumnName("prsactividad")
                    .IsFixedLength();

                entity.Property(e => e.Prsactividad2)
                    .HasMaxLength(20)
                    .HasColumnName("prsactividad2")
                    .IsFixedLength();

                entity.Property(e => e.Prsactividadhacer).HasColumnName("prsactividadhacer");

                entity.Property(e => e.Prsactivo).HasColumnName("prsactivo");

                entity.Property(e => e.Prsacuerdo).HasColumnName("prsacuerdo");

                entity.Property(e => e.PrsacuerdoBecas).HasColumnName("prsacuerdo_becas");

                entity.Property(e => e.PrsacuerdoContrato).HasColumnName("prsacuerdo_contrato");

                entity.Property(e => e.Prsacuerdofecha)
                    .HasColumnType("timestamp without time zone")
                    .HasColumnName("prsacuerdofecha");

                entity.Property(e => e.Prsacusado).HasColumnName("prsacusado");

                entity.Property(e => e.Prsamaterno)
                    .HasMaxLength(50)
                    .HasColumnName("prsamaterno")
                    .IsFixedLength();

                entity.Property(e => e.Prsapaterno)
                    .HasMaxLength(50)
                    .HasColumnName("prsapaterno")
                    .IsFixedLength();

                entity.Property(e => e.Prsbeca).HasColumnName("prsbeca");

                entity.Property(e => e.PrsbecaAcade)
                    .HasMaxLength(1)
                    .HasColumnName("prsbeca_acade");

                entity.Property(e => e.PrsbecaConv)
                    .HasMaxLength(1)
                    .HasColumnName("prsbeca_conv");

                entity.Property(e => e.PrsbecaExa)
                    .HasMaxLength(1)
                    .HasColumnName("prsbeca_exa");

                entity.Property(e => e.PrsbecaHerma)
                    .HasMaxLength(1)
                    .HasColumnName("prsbeca_herma");

                entity.Property(e => e.PrsbecaTalento)
                    .HasMaxLength(1)
                    .HasColumnName("prsbeca_talento");

                entity.Property(e => e.Prscarrera).HasColumnName("prscarrera");

                entity.Property(e => e.Prscarrera2).HasColumnName("prscarrera2");

                entity.Property(e => e.Prscarrera3).HasColumnName("prscarrera3");

                entity.Property(e => e.Prscarrera4).HasColumnName("prscarrera4");

                entity.Property(e => e.Prscolegiatura)
                    .HasMaxLength(10)
                    .HasColumnName("prscolegiatura")
                    .IsFixedLength();

                entity.Property(e => e.Prsconoceinter)
                    .HasMaxLength(1)
                    .HasColumnName("prsconoceinter");

                entity.Property(e => e.Prsconocerinter)
                    .HasMaxLength(1)
                    .HasColumnName("prsconocerinter");

                entity.Property(e => e.Prscontratokey)
                    .HasMaxLength(200)
                    .HasColumnName("prscontratokey")
                    .IsFixedLength();

                entity.Property(e => e.Prsconvenio)
                    .HasMaxLength(10)
                    .HasColumnName("prsconvenio")
                    .IsFixedLength();

                entity.Property(e => e.Prscorreo)
                    .HasMaxLength(100)
                    .HasColumnName("prscorreo");

                entity.Property(e => e.Prscorreo2)
                    .HasMaxLength(100)
                    .HasColumnName("prscorreo2");

                entity.Property(e => e.Prscurp)
                    .HasMaxLength(18)
                    .HasColumnName("prscurp")
                    .IsFixedLength();

                entity.Property(e => e.Prsdesc)
                    .HasPrecision(10, 2)
                    .HasColumnName("prsdesc");

                entity.Property(e => e.Prsdomicilio)
                    .HasMaxLength(200)
                    .HasColumnName("prsdomicilio")
                    .IsFixedLength();

                entity.Property(e => e.Prsedad).HasColumnName("prsedad");

                entity.Property(e => e.Prsedoescuela).HasColumnName("prsedoescuela");

                entity.Property(e => e.Prselegida).HasColumnName("prselegida");

                entity.Property(e => e.Prselegida2).HasColumnName("prselegida2");

                entity.Property(e => e.Prselegida3).HasColumnName("prselegida3");

                entity.Property(e => e.Prsemergenciacel)
                    .HasMaxLength(20)
                    .HasColumnName("prsemergenciacel")
                    .IsFixedLength();

                entity.Property(e => e.Prsemergenciadom)
                    .HasMaxLength(200)
                    .HasColumnName("prsemergenciadom")
                    .IsFixedLength();

                entity.Property(e => e.Prsemergenciaemail)
                    .HasMaxLength(100)
                    .HasColumnName("prsemergenciaemail");

                entity.Property(e => e.Prsemergenciaparentesco)
                    .HasMaxLength(20)
                    .HasColumnName("prsemergenciaparentesco")
                    .IsFixedLength();

                entity.Property(e => e.Prsemergenciatel)
                    .HasMaxLength(20)
                    .HasColumnName("prsemergenciatel")
                    .IsFixedLength();

                entity.Property(e => e.Prsempresa)
                    .HasMaxLength(20)
                    .HasColumnName("prsempresa")
                    .IsFixedLength();

                entity.Property(e => e.Prsempresadom)
                    .HasMaxLength(150)
                    .HasColumnName("prsempresadom")
                    .IsFixedLength();

                entity.Property(e => e.Prsempresapuesto)
                    .HasMaxLength(20)
                    .HasColumnName("prsempresapuesto")
                    .IsFixedLength();

                entity.Property(e => e.Prsempresatel)
                    .HasMaxLength(20)
                    .HasColumnName("prsempresatel")
                    .IsFixedLength();

                entity.Property(e => e.Prsescuela).HasColumnName("prsescuela");

                entity.Property(e => e.Prsescueladom)
                    .HasMaxLength(200)
                    .HasColumnName("prsescueladom")
                    .IsFixedLength();

                entity.Property(e => e.Prsescuelap)
                    .HasMaxLength(200)
                    .HasColumnName("prsescuelap")
                    .IsFixedLength();

                entity.Property(e => e.Prsescuelapestado).HasColumnName("prsescuelapestado");

                entity.Property(e => e.Prsescuelapmunicipio).HasColumnName("prsescuelapmunicipio");

                entity.Property(e => e.Prsestadocivil).HasColumnName("prsestadocivil");

                entity.Property(e => e.Prsestatus).HasColumnName("prsestatus");

                entity.Property(e => e.Prsestatussol).HasColumnName("prsestatussol");

                entity.Property(e => e.Prsestudio).HasColumnName("prsestudio");

                entity.Property(e => e.Prsestudios)
                    .HasMaxLength(400)
                    .HasColumnName("prsestudios")
                    .IsFixedLength();

                entity.Property(e => e.Prsextranjero)
                    .HasMaxLength(1)
                    .HasColumnName("prsextranjero");

                entity.Property(e => e.Prsfacebook)
                    .HasMaxLength(100)
                    .HasColumnName("prsfacebook")
                    .IsFixedLength();

                entity.Property(e => e.Prsfechaeentrega)
                    .HasColumnType("timestamp without time zone")
                    .HasColumnName("prsfechaeentrega");

                entity.Property(e => e.Prsfechafine).HasColumnName("prsfechafine");

                entity.Property(e => e.Prsfechanac).HasColumnName("prsfechanac");

                entity.Property(e => e.Prsfechar).HasColumnName("prsfechar");

                entity.Property(e => e.Prsferia).HasColumnName("prsferia");

                entity.Property(e => e.Prsfiltro).HasColumnName("prsfiltro");

                entity.Property(e => e.Prsimporte)
                    .HasPrecision(14, 2)
                    .HasColumnName("prsimporte");

                entity.Property(e => e.Prsimportecuotaadmin)
                    .HasPrecision(8, 2)
                    .HasColumnName("prsimportecuotaadmin");

                entity.Property(e => e.Prsimporteinscripcion)
                    .HasPrecision(8, 2)
                    .HasColumnName("prsimporteinscripcion");

                entity.Property(e => e.Prsimporteparcialidad)
                    .HasPrecision(8, 2)
                    .HasColumnName("prsimporteparcialidad");

                entity.Property(e => e.Prsingresomensual)
                    .HasPrecision(17, 4)
                    .HasColumnName("prsingresomensual");

                entity.Property(e => e.Prsinicioclases)
                    .HasMaxLength(1)
                    .HasColumnName("prsinicioclases");

                entity.Property(e => e.Prsinscb)
                    .HasPrecision(5, 2)
                    .HasColumnName("prsinscb");

                entity.Property(e => e.Prsinscrito).HasColumnName("prsinscrito");

                entity.Property(e => e.Prsinterid).HasColumnName("prsinterid");

                entity.Property(e => e.Prslugarnac)
                    .HasMaxLength(50)
                    .HasColumnName("prslugarnac")
                    .IsFixedLength();

                entity.Property(e => e.Prsmedio).HasColumnName("prsmedio");

                entity.Property(e => e.Prsmeespec)
                    .HasMaxLength(1)
                    .HasColumnName("prsmeespec");

                entity.Property(e => e.Prsmeface)
                    .HasMaxLength(1)
                    .HasColumnName("prsmeface");

                entity.Property(e => e.Prsmeotro)
                    .HasMaxLength(20)
                    .HasColumnName("prsmeotro")
                    .IsFixedLength();

                entity.Property(e => e.Prsmepag)
                    .HasMaxLength(1)
                    .HasColumnName("prsmepag");

                entity.Property(e => e.Prsmerad)
                    .HasMaxLength(1)
                    .HasColumnName("prsmerad");

                entity.Property(e => e.Prsmerevista)
                    .HasMaxLength(1)
                    .HasColumnName("prsmerevista");

                entity.Property(e => e.Prsmes).HasColumnName("prsmes");

                entity.Property(e => e.Prsmetv)
                    .HasMaxLength(1)
                    .HasColumnName("prsmetv");

                entity.Property(e => e.Prsmodalidad).HasColumnName("prsmodalidad");

                entity.Property(e => e.Prsmodfecha).HasColumnName("prsmodfecha");

                entity.Property(e => e.Prsmodhora)
                    .HasMaxLength(8)
                    .HasColumnName("prsmodhora")
                    .IsFixedLength();

                entity.Property(e => e.Prsmodprog)
                    .HasMaxLength(500)
                    .HasColumnName("prsmodprog")
                    .IsFixedLength();

                entity.Property(e => e.Prsmodusuario).HasColumnName("prsmodusuario");

                entity.Property(e => e.Prsmotivo).HasColumnName("prsmotivo");

                entity.Property(e => e.Prsmunesc).HasColumnName("prsmunesc");

                entity.Property(e => e.Prsmunicipio)
                    .HasMaxLength(50)
                    .HasColumnName("prsmunicipio")
                    .IsFixedLength();

                entity.Property(e => e.Prsnacionalidad)
                    .HasMaxLength(20)
                    .HasColumnName("prsnacionalidad")
                    .IsFixedLength();

                entity.Property(e => e.Prsnocontrol)
                    .HasMaxLength(20)
                    .HasColumnName("prsnocontrol")
                    .IsFixedLength();

                entity.Property(e => e.Prsnombre)
                    .HasMaxLength(50)
                    .HasColumnName("prsnombre")
                    .IsFixedLength();

                entity.Property(e => e.Prsnombreconyugue)
                    .HasMaxLength(100)
                    .HasColumnName("prsnombreconyugue")
                    .IsFixedLength();

                entity.Property(e => e.Prsnombreemergencia)
                    .HasMaxLength(100)
                    .HasColumnName("prsnombreemergencia")
                    .IsFixedLength();

                entity.Property(e => e.Prsnoverifica)
                    .HasMaxLength(1)
                    .HasColumnName("prsnoverifica");

                entity.Property(e => e.Prsobservaciones).HasColumnName("prsobservaciones");

                entity.Property(e => e.Prspadecimientob).HasColumnName("prspadecimientob");

                entity.Property(e => e.Prspadecimientonombre)
                    .HasMaxLength(40)
                    .HasColumnName("prspadecimientonombre")
                    .IsFixedLength();

                entity.Property(e => e.Prspag).HasColumnName("prspag");

                entity.Property(e => e.Prsparcb)
                    .HasPrecision(5, 2)
                    .HasColumnName("prsparcb");

                entity.Property(e => e.Prspbeca).HasColumnName("prspbeca");

                entity.Property(e => e.Prspbecab)
                    .HasMaxLength(50)
                    .HasColumnName("prspbecab")
                    .IsFixedLength();

                entity.Property(e => e.Prspbecaporcentaje).HasColumnName("prspbecaporcentaje");

                entity.Property(e => e.Prspbecapormen).HasColumnName("prspbecapormen");

                entity.Property(e => e.Prspbecatipo)
                    .HasMaxLength(5)
                    .HasColumnName("prspbecatipo")
                    .IsFixedLength();

                entity.Property(e => e.Prsperiodo)
                    .HasMaxLength(10)
                    .HasColumnName("prsperiodo")
                    .IsFixedLength();

                entity.Property(e => e.Prspromedio)
                    .HasPrecision(9, 4)
                    .HasColumnName("prspromedio");

                entity.Property(e => e.Prspsico).HasColumnName("prspsico");

                entity.Property(e => e.Prspyear).HasColumnName("prspyear");

                entity.Property(e => e.Prsrcorigen)
                    .HasMaxLength(30)
                    .HasColumnName("prsrcorigen")
                    .IsFixedLength();

                entity.Property(e => e.Prsregfecha).HasColumnName("prsregfecha");

                entity.Property(e => e.Prsreghora)
                    .HasMaxLength(8)
                    .HasColumnName("prsreghora")
                    .IsFixedLength();

                entity.Property(e => e.Prsregistoonline).HasColumnName("prsregistoonline");

                entity.Property(e => e.Prsregprog)
                    .HasMaxLength(128)
                    .HasColumnName("prsregprog")
                    .IsFixedLength();

                entity.Property(e => e.Prsregusuario).HasColumnName("prsregusuario");

                entity.Property(e => e.Prsrescuela)
                    .HasMaxLength(50)
                    .HasColumnName("prsrescuela")
                    .IsFixedLength();

                entity.Property(e => e.Prsrevalida)
                    .HasMaxLength(1)
                    .HasColumnName("prsrevalida");

                entity.Property(e => e.Prsrfc)
                    .HasMaxLength(18)
                    .HasColumnName("prsrfc")
                    .IsFixedLength();

                entity.Property(e => e.Prsseguromedico)
                    .HasMaxLength(20)
                    .HasColumnName("prsseguromedico")
                    .IsFixedLength();

                entity.Property(e => e.Prssemestre).HasColumnName("prssemestre");

                entity.Property(e => e.Prssexo)
                    .HasMaxLength(1)
                    .HasColumnName("prssexo");

                entity.Property(e => e.Prstamizaje)
                    .HasMaxLength(20)
                    .HasColumnName("prstamizaje")
                    .IsFixedLength();

                entity.Property(e => e.Prstapmaterno)
                    .HasMaxLength(50)
                    .HasColumnName("prstapmaterno")
                    .IsFixedLength();

                entity.Property(e => e.Prstappaterno)
                    .HasMaxLength(50)
                    .HasColumnName("prstappaterno")
                    .IsFixedLength();

                entity.Property(e => e.Prstaprobacion).HasColumnName("prstaprobacion");

                entity.Property(e => e.Prstcorreo)
                    .HasMaxLength(100)
                    .HasColumnName("prstcorreo");

                entity.Property(e => e.Prstdomicilio)
                    .HasMaxLength(600)
                    .HasColumnName("prstdomicilio")
                    .IsFixedLength();

                entity.Property(e => e.Prstelefono)
                    .HasMaxLength(20)
                    .HasColumnName("prstelefono")
                    .IsFixedLength();

                entity.Property(e => e.Prstelefono2)
                    .HasMaxLength(20)
                    .HasColumnName("prstelefono2")
                    .IsFixedLength();

                entity.Property(e => e.Prstelefonom)
                    .HasMaxLength(20)
                    .HasColumnName("prstelefonom")
                    .IsFixedLength();

                entity.Property(e => e.Prstelefonom2)
                    .HasMaxLength(20)
                    .HasColumnName("prstelefonom2")
                    .IsFixedLength();

                entity.Property(e => e.Prstipob)
                    .HasMaxLength(5)
                    .HasColumnName("prstipob")
                    .IsFixedLength();

                entity.Property(e => e.Prstipoesc)
                    .HasMaxLength(1)
                    .HasColumnName("prstipoesc");

                entity.Property(e => e.Prstiposangre)
                    .HasMaxLength(10)
                    .HasColumnName("prstiposangre")
                    .IsFixedLength();

                entity.Property(e => e.Prstnombre)
                    .HasMaxLength(200)
                    .HasColumnName("prstnombre")
                    .IsFixedLength();

                entity.Property(e => e.Prsttelefono)
                    .HasMaxLength(10)
                    .HasColumnName("prsttelefono")
                    .IsFixedLength();

                entity.Property(e => e.Prstwitter)
                    .HasMaxLength(100)
                    .HasColumnName("prstwitter")
                    .IsFixedLength();

                entity.Property(e => e.Prsyear).HasColumnName("prsyear");

                entity.Property(e => e.Psrfechainicioe).HasColumnName("psrfechainicioe");

                entity.Property(e => e.Psrsuspendido).HasColumnName("psrsuspendido");

                entity.Property(e => e.Usuid).HasColumnName("usuid");
            });

            modelBuilder.Entity<Tusuario>(entity =>
            {
                entity.HasKey(e => e.Usuid)
                    .HasName("tusuario_pkey");

                entity.ToTable("tusuario");

                entity.Property(e => e.Usuid)
                    .ValueGeneratedNever()
                    .HasColumnName("usuid");

                entity.Property(e => e.Altared)
                    .HasColumnName("altared")
                    .HasDefaultValueSql("0");

                entity.Property(e => e.Anocontrol)
                    .HasMaxLength(20)
                    .HasColumnName("anocontrol")
                    .IsFixedLength();

                entity.Property(e => e.Cambiocontra)
                    .HasColumnName("cambiocontra")
                    .HasDefaultValueSql("0");

                entity.Property(e => e.Crmid).HasColumnName("crmid");

                entity.Property(e => e.Enviocorreo).HasColumnName("enviocorreo");

                entity.Property(e => e.Redpassword)
                    .HasMaxLength(20)
                    .HasColumnName("redpassword")
                    .IsFixedLength();

                entity.Property(e => e.Usuactivo).HasColumnName("usuactivo");

                entity.Property(e => e.Usucambiocontra)
                    .HasColumnName("usucambiocontra")
                    .HasDefaultValueSql("0");

                entity.Property(e => e.Usuequipo)
                    .HasMaxLength(150)
                    .HasColumnName("usuequipo")
                    .IsFixedLength();

                entity.Property(e => e.Usuimagemov).HasColumnName("usuimagemov");

                entity.Property(e => e.UsuimagemovGxi)
                    .HasMaxLength(2048)
                    .HasColumnName("usuimagemov_gxi");

                entity.Property(e => e.Usuip)
                    .HasMaxLength(20)
                    .HasColumnName("usuip")
                    .IsFixedLength();

                entity.Property(e => e.Usukey)
                    .HasMaxLength(32)
                    .HasColumnName("usukey")
                    .IsFixedLength();

                entity.Property(e => e.Usulastpasschange).HasColumnName("usulastpasschange");

                entity.Property(e => e.Usumodulo)
                    .IsRequired()
                    .HasMaxLength(10)
                    .HasColumnName("usumodulo")
                    .IsFixedLength();

                entity.Property(e => e.Usumoodle)
                    .HasMaxLength(120)
                    .HasColumnName("usumoodle")
                    .IsFixedLength();

                entity.Property(e => e.Usumoodleid).HasColumnName("usumoodleid");

                entity.Property(e => e.Usumoodleidb).HasColumnName("usumoodleidb");

                entity.Property(e => e.Usumoodleidm).HasColumnName("usumoodleidm");

                entity.Property(e => e.Usumovil).HasColumnName("usumovil");

                entity.Property(e => e.Usupassword)
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnName("usupassword")
                    .IsFixedLength();

                entity.Property(e => e.Usuperfil)
                    .IsRequired()
                    .HasMaxLength(10)
                    .HasColumnName("usuperfil")
                    .IsFixedLength();

                entity.Property(e => e.Ususession).HasColumnName("ususession");

                entity.Property(e => e.Usuusesion)
                    .HasColumnType("timestamp without time zone")
                    .HasColumnName("usuusesion");

                entity.Property(e => e.Usuusuario)
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnName("usuusuario")
                    .IsFixedLength();
            });

            modelBuilder.HasSequence("apuestos_apid_seq").StartsAt(18);

            modelBuilder.HasSequence("ccbeca_beid_seq").StartsAt(423);

            modelBuilder.HasSequence("cceventos_eventoid_seq").StartsAt(2);

            modelBuilder.HasSequence("cereporteid");

            modelBuilder.HasSequence("encargados_rpid_seq").StartsAt(6);

            modelBuilder.HasSequence("id_usr_acc");

            modelBuilder.HasSequence("id_usr_mod");

            modelBuilder.HasSequence("idbregistro");

            modelBuilder.HasSequence("idrecl");

            modelBuilder.HasSequence("otid").StartsAt(2);

            modelBuilder.HasSequence("prsid").StartsAt(12);

            modelBuilder.HasSequence("rPayuRegistro_rPayuRegistroid_seq").StartsAt(21);

            modelBuilder.HasSequence("taaplicaciones_apliid_seq").StartsAt(2);

            modelBuilder.HasSequence("tabitacoracorreos_biid_seq").StartsAt(176);

            modelBuilder.HasSequence("tacomentario_comentarioid_seq").StartsAt(36);

            modelBuilder.HasSequence("taconfiguracion_aconid_seq").StartsAt(2);

            modelBuilder.HasSequence("tagenda_ageid_seq");

            modelBuilder.HasSequence("tagrupo_agruid_seq").StartsAt(1308);

            modelBuilder.HasSequence("talumnocarrera_alcid_seq").StartsAt(450);

            modelBuilder.HasSequence("tamateriaimpartir_amaiid_seq").StartsAt(68);

            modelBuilder.HasSequence("tanoticias_noticiaid_seq").StartsAt(8);

            modelBuilder.HasSequence("tarea_areid_seq").StartsAt(4);

            modelBuilder.HasSequence("tareglamento_reglamentoid_seq").StartsAt(35);

            modelBuilder.HasSequence("tbeneficio_benid_seq");

            modelBuilder.HasSequence("tcarrera_carid_seq").StartsAt(7);

            modelBuilder.HasSequence("tcita_citid_seq");

            modelBuilder.HasSequence("tcobranza_cbrid_seq");

            modelBuilder.HasSequence("tcobranzacuenta_ctaid_seq");

            modelBuilder.HasSequence("tcod_tcoid_seq");

            modelBuilder.HasSequence("tcodigo_codid_seq").StartsAt(3327);

            modelBuilder.HasSequence("tcompany_comid_seq");

            modelBuilder.HasSequence("tconfiguracion_cfgid_seq");

            modelBuilder.HasSequence("tcontacto_conid_seq");

            modelBuilder.HasSequence("tcrm_crmid_seq").StartsAt(954);

            modelBuilder.HasSequence("tctabanco_ctbid_seq");

            modelBuilder.HasSequence("tcuestionario_cueid_seq");

            modelBuilder.HasSequence("tescala_idescala_seq").StartsAt(2);

            modelBuilder.HasSequence("texpediente_expid_seq");

            modelBuilder.HasSequence("tfolio_folid_seq");

            modelBuilder.HasSequence("totro_otrid_seq");

            modelBuilder.HasSequence("tpago_pgoid_seq");

            modelBuilder.HasSequence("tpagocuenta_ptaid_seq");

            modelBuilder.HasSequence("tpagos_pagid_seq");

            modelBuilder.HasSequence("tpatron_ptrid_seq");

            modelBuilder.HasSequence("tplanasignado1_pasid_seq");

            modelBuilder.HasSequence("tplancues_pcuid_seq");

            modelBuilder.HasSequence("tprospecto_prsid_seq");

            modelBuilder.HasSequence("tprospectohistorial_prhid_seq");

            modelBuilder.HasSequence("tprueba_idprueba_seq").StartsAt(3);

            modelBuilder.HasSequence("tpruebaaplicacion_idtpa_seq").StartsAt(4);

            modelBuilder.HasSequence("tpruebaprefiles_idperfil_seq").StartsAt(6);

            modelBuilder.HasSequence("trecibo_rboid_seq");

            modelBuilder.HasSequence("tregdel_delid_seq");

            modelBuilder.HasSequence("tseguimiento_segid_seq");

            modelBuilder.HasSequence("ttmprbo_tboid_seq");

            modelBuilder.HasSequence("tusuario_id_seq");

            modelBuilder.HasSequence("tusuario_usuid_seq").StartsAt(1092);

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}