// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CentinelaV3.Data.npsql
{
    public partial class Tapreinscrito
    {
        public long Preid { get; set; }
        public long Aluid { get; set; }
        public long Aacfid { get; set; }
        public bool? Prepag { get; set; }
        public DateTime? Prepagreg { get; set; }
        public long? Prepagusuid { get; set; }
        public bool? Preee { get; set; }
        public DateTime? Preeereg { get; set; }
        public bool? Predoc { get; set; }
        public long? Predocusuid { get; set; }
        public DateTime? Predocreg { get; set; }
        public bool? Prereg { get; set; }
        public DateTime? Preregreg { get; set; }
        public bool? Prehorario { get; set; }
        public long? Prehorariousuid { get; set; }
        public DateTime? Prehorarioreg { get; set; }
        public short? Preanio { get; set; }
        public short? Preperiodo { get; set; }
        public string Pretipo { get; set; }
        public bool? Prebeca { get; set; }
        public bool? Prebecaa { get; set; }
        public DateTime? Prebecareg { get; set; }
        public short? Prebecausuid { get; set; }
        public bool? Preesquema { get; set; }
        public DateTime? Preesquemareg { get; set; }
        public long? Preesquemausuid { get; set; }

        public virtual Talumno Alu { get; set; }
    }
}