// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CentinelaV3.Data.npsql
{
    public partial class Tusuario
    {
        public long Usuid { get; set; }
        public long Crmid { get; set; }
        public string Usuusuario { get; set; }
        public string Usupassword { get; set; }
        public string Usumodulo { get; set; }
        public short Usuactivo { get; set; }
        public string Usuperfil { get; set; }
        public short Ususession { get; set; }
        public short? Altared { get; set; }
        public string Redpassword { get; set; }
        public short? Enviocorreo { get; set; }
        public DateTime? Usuusesion { get; set; }
        public string Anocontrol { get; set; }
        public string Usumoodle { get; set; }
        public short? Usumoodleid { get; set; }
        public short? Usumoodleidb { get; set; }
        public short? Cambiocontra { get; set; }
        public short? Usucambiocontra { get; set; }
        public short? Usumoodleidm { get; set; }
        public string UsuimagemovGxi { get; set; }
        public byte[] Usuimagemov { get; set; }
        public short? Usumovil { get; set; }
        public string Usuip { get; set; }
        public string Usuequipo { get; set; }
        public string Usukey { get; set; }
        public DateTime? Usulastpasschange { get; set; }
    }
}