// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CentinelaV3.Data.sql
{
    public partial class Niveles
    {
        public Niveles()
        {
            Carreras = new HashSet<Carreras>();
            ListaPrecios = new HashSet<ListaPrecios>();
        }

        public int NivelId { get; set; }
        public string NivelNombre { get; set; }
        public string NivelDescripcion { get; set; }

        public virtual ICollection<Carreras> Carreras { get; set; }
        public virtual ICollection<ListaPrecios> ListaPrecios { get; set; }
    }
}