// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CentinelaV3.Data.sql
{
    public partial class Usuario
    {
        public Usuario()
        {
            BecaAlumno = new HashSet<BecaAlumno>();
            Becaalubitacora = new HashSet<Becaalubitacora>();
            Campana = new HashSet<Campana>();
            Carreras = new HashSet<Carreras>();
            GeneralesProspecto = new HashSet<GeneralesProspecto>();
        }

        public long Usuid { get; set; }
        public int Rolid { get; set; }
        public string Usuusuario { get; set; }
        public string Usupassword { get; set; }
        public string Usutipo { get; set; }
        public long? Usuidtipo { get; set; }
        public string Usukey { get; set; }
        public bool Usuactivo { get; set; }
        public short? UsumoodleP { get; set; }
        public short? UsumoodleL { get; set; }
        public short? UsumoodleM { get; set; }
        public string Usumovil { get; set; }
        public string Usuip { get; set; }
        public decimal Usupid { get; set; }
        public string Usuequipo { get; set; }
        public byte[] Usuimage { get; set; }
        public DateTime? UsulastChange { get; set; }
        public DateTime? Ususession { get; set; }

        public virtual ICollection<BecaAlumno> BecaAlumno { get; set; }
        public virtual ICollection<Becaalubitacora> Becaalubitacora { get; set; }
        public virtual ICollection<Campana> Campana { get; set; }
        public virtual ICollection<Carreras> Carreras { get; set; }
        public virtual ICollection<GeneralesProspecto> GeneralesProspecto { get; set; }
    }
}